// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: geostats/data.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Data struct {
	Id           uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Requester    string `protobuf:"bytes,2,opt,name=requester,proto3" json:"requester,omitempty"`
	AggX         string `protobuf:"bytes,3,opt,name=aggX,proto3" json:"aggX,omitempty"`
	DatasetCode  string `protobuf:"bytes,4,opt,name=datasetCode,proto3" json:"datasetCode,omitempty"`
	SelectedBand string `protobuf:"bytes,5,opt,name=selectedBand,proto3" json:"selectedBand,omitempty"`
	ImageScale   string `protobuf:"bytes,6,opt,name=imageScale,proto3" json:"imageScale,omitempty"`
	StartDate    string `protobuf:"bytes,7,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate      string `protobuf:"bytes,8,opt,name=endDate,proto3" json:"endDate,omitempty"`
	Creator      string `protobuf:"bytes,9,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_95abc1b9b0eb3c56, []int{0}
}
func (m *Data) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Data.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return m.Size()
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Data) GetRequester() string {
	if m != nil {
		return m.Requester
	}
	return ""
}

func (m *Data) GetAggX() string {
	if m != nil {
		return m.AggX
	}
	return ""
}

func (m *Data) GetDatasetCode() string {
	if m != nil {
		return m.DatasetCode
	}
	return ""
}

func (m *Data) GetSelectedBand() string {
	if m != nil {
		return m.SelectedBand
	}
	return ""
}

func (m *Data) GetImageScale() string {
	if m != nil {
		return m.ImageScale
	}
	return ""
}

func (m *Data) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *Data) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

func (m *Data) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*Data)(nil), "shamba.geostats.geostats.Data")
}

func init() { proto.RegisterFile("geostats/data.proto", fileDescriptor_95abc1b9b0eb3c56) }

var fileDescriptor_95abc1b9b0eb3c56 = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0xeb, 0x10, 0x5a, 0x62, 0x10, 0x83, 0x59, 0x3c, 0x20, 0x2b, 0xea, 0x54, 0x09, 0x29,
	0x19, 0x78, 0x83, 0x52, 0x5e, 0xa0, 0x2c, 0x88, 0xed, 0x12, 0x9f, 0xdc, 0x48, 0x4d, 0x5d, 0xec,
	0xab, 0x04, 0x1b, 0x8f, 0xc0, 0x63, 0x31, 0x76, 0x64, 0x44, 0xc9, 0x8b, 0xa0, 0x38, 0x34, 0x2d,
	0xdb, 0x7f, 0xdf, 0x77, 0xd2, 0x9d, 0x7e, 0x7e, 0x63, 0xd0, 0x7a, 0x02, 0xf2, 0xb9, 0x06, 0x82,
	0x6c, 0xeb, 0x2c, 0x59, 0x21, 0xfd, 0x0a, 0xea, 0x02, 0xb2, 0x83, 0x1b, 0xc2, 0xf4, 0x23, 0xe2,
	0xf1, 0x02, 0x08, 0xc4, 0x35, 0x8f, 0x2a, 0x2d, 0x59, 0xca, 0x66, 0xf1, 0x32, 0xaa, 0xb4, 0xb8,
	0xe5, 0x89, 0xc3, 0xd7, 0x1d, 0x7a, 0x42, 0x27, 0xa3, 0x94, 0xcd, 0x92, 0xe5, 0x11, 0x08, 0xc1,
	0x63, 0x30, 0xe6, 0x59, 0x9e, 0x05, 0x11, 0xb2, 0x48, 0xf9, 0x65, 0x77, 0xd2, 0x23, 0x3d, 0x58,
	0x8d, 0x32, 0x0e, 0xea, 0x14, 0x89, 0x29, 0xbf, 0xf2, 0xb8, 0xc6, 0x92, 0x50, 0xcf, 0x61, 0xa3,
	0xe5, 0x79, 0x58, 0xf9, 0xc7, 0x84, 0xe2, 0xbc, 0xaa, 0xc1, 0xe0, 0x53, 0x09, 0x6b, 0x94, 0xe3,
	0xb0, 0x71, 0x42, 0xba, 0xbf, 0x3c, 0x81, 0xa3, 0x05, 0x10, 0xca, 0x49, 0xff, 0xd7, 0x00, 0x84,
	0xe4, 0x13, 0xdc, 0xe8, 0xe0, 0x2e, 0x82, 0x3b, 0x8c, 0x9d, 0x29, 0x1d, 0x02, 0x59, 0x27, 0x93,
	0xde, 0xfc, 0x8d, 0xf3, 0xc7, 0xaf, 0x46, 0xb1, 0x7d, 0xa3, 0xd8, 0x4f, 0xa3, 0xd8, 0x67, 0xab,
	0x46, 0xfb, 0x56, 0x8d, 0xbe, 0x5b, 0x35, 0x7a, 0xb9, 0x33, 0x15, 0xad, 0x76, 0x45, 0x56, 0xda,
	0x3a, 0xef, 0x1b, 0xcc, 0x87, 0x76, 0xdf, 0x8e, 0x91, 0xde, 0xb7, 0xe8, 0x8b, 0x71, 0xa8, 0xfa,
	0xfe, 0x37, 0x00, 0x00, 0xff, 0xff, 0x12, 0xbf, 0xd6, 0x70, 0x81, 0x01, 0x00, 0x00,
}

func (m *Data) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Data) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Data) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintData(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.EndDate) > 0 {
		i -= len(m.EndDate)
		copy(dAtA[i:], m.EndDate)
		i = encodeVarintData(dAtA, i, uint64(len(m.EndDate)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.StartDate) > 0 {
		i -= len(m.StartDate)
		copy(dAtA[i:], m.StartDate)
		i = encodeVarintData(dAtA, i, uint64(len(m.StartDate)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.ImageScale) > 0 {
		i -= len(m.ImageScale)
		copy(dAtA[i:], m.ImageScale)
		i = encodeVarintData(dAtA, i, uint64(len(m.ImageScale)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.SelectedBand) > 0 {
		i -= len(m.SelectedBand)
		copy(dAtA[i:], m.SelectedBand)
		i = encodeVarintData(dAtA, i, uint64(len(m.SelectedBand)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.DatasetCode) > 0 {
		i -= len(m.DatasetCode)
		copy(dAtA[i:], m.DatasetCode)
		i = encodeVarintData(dAtA, i, uint64(len(m.DatasetCode)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.AggX) > 0 {
		i -= len(m.AggX)
		copy(dAtA[i:], m.AggX)
		i = encodeVarintData(dAtA, i, uint64(len(m.AggX)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Requester) > 0 {
		i -= len(m.Requester)
		copy(dAtA[i:], m.Requester)
		i = encodeVarintData(dAtA, i, uint64(len(m.Requester)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintData(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintData(dAtA []byte, offset int, v uint64) int {
	offset -= sovData(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Data) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovData(uint64(m.Id))
	}
	l = len(m.Requester)
	if l > 0 {
		n += 1 + l + sovData(uint64(l))
	}
	l = len(m.AggX)
	if l > 0 {
		n += 1 + l + sovData(uint64(l))
	}
	l = len(m.DatasetCode)
	if l > 0 {
		n += 1 + l + sovData(uint64(l))
	}
	l = len(m.SelectedBand)
	if l > 0 {
		n += 1 + l + sovData(uint64(l))
	}
	l = len(m.ImageScale)
	if l > 0 {
		n += 1 + l + sovData(uint64(l))
	}
	l = len(m.StartDate)
	if l > 0 {
		n += 1 + l + sovData(uint64(l))
	}
	l = len(m.EndDate)
	if l > 0 {
		n += 1 + l + sovData(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovData(uint64(l))
	}
	return n
}

func sovData(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozData(x uint64) (n int) {
	return sovData(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Data) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Data: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Data: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Requester", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Requester = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AggX", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AggX = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DatasetCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DatasetCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SelectedBand", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SelectedBand = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ImageScale", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ImageScale = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartDate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StartDate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndDate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EndDate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipData(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipData(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowData
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthData
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupData
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthData
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthData        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowData          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupData = fmt.Errorf("proto: unexpected end of group")
)
